# Generated by Django 2.2.24 on 2026-08-26 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EolDiscussionXBlockNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_id', models.CharField(db_index=True, max_length=255)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('block_key', opaque_keys.edx.django.models.UsageKeyField(default=None, max_length=255)),
                ('daily_threads', models.IntegerField(default=0)),
                ('daily_comment', models.IntegerField(default=0)),
                ('weekly_threads', models.IntegerField(default=0)),
                ('weekly_comment', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('discussion_id', 'course_id')},
                'index_together': {('discussion_id', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='EolDiscussionXBlockNotificationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_often', models.TextField(choices=[('never', 'never'), ('daily', 'daily'), ('weekly', 'weekly')], default='never')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eoldiscussion.EolDiscussionXBlockNotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discussion', 'user')},
                'index_together': {('discussion', 'user')},
            },
        ),
    ]
